project_name: dev-ca
builds:
  - env:
      - CGO_ENABLED=0
    binary: dev-ca
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    hooks:
      post: ./upx.sh
archive:
  format: zip
  replacements:
    darwin: MacOSX
    linux: Linux
    windows: Windows
    386: 32-Bit
    amd64: 64-Bit
  files:
    - LICENSE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true